# Example careauth configuration file

################################################################################
# Web settings
################################################################################

# External TCP port for proxy to listen on for client connections
# default = 3000
port: 3000

# Domain for the site (used for subdomains such as openid.domain and fhir.domain)
domain: 'localhost'

# Whether or not to use TLS encryption ('false' for http, 'true' for https)
# default = false
use_tls: false

# Whether or not to adhere to more stringent, more secure NSA Suite B encryption
# This limits connections to using TLS v1.2 and specific Suite B-compliant ciphers
# This only has an effect if 'use_tls' is set to 'true'
# WARNING! This will only work if you have a certificate with an ECDSA key!
# default = false
use_suite_b: false

# The TLS key/certificate file and password (needed if use_tls is set to 'true')
tls_keystore_file: tls/key-and-cert.pfx
tls_keystore_pass: password

# Targets to proxy connections for the server's subdomains
# If these are empty, the targets will be auto-generated based on the
#   domain and port that those services listen on by default
# If these are non-empty, they MUST be formatted as a valid URL,
#   e.g. 'http://example.com/route'
proxy_careshare:        '' # domain, www.domain
proxy_careshare_remote: '' # remote.domain
proxy_fhir:             '' # fhir.domain
proxy_openid:           '' # openid.domain
proxy_api:              '' # api.domain

################################################################################
# Database settings
################################################################################

# MongoDB database url
# These values can also be controlled by the "db_production" and "db_test"
# environment variables
db:
    production: 'mongodb://localhost/careauth_production_db'
    test: 'mongodb://localhost/careauth_test_db'

################################################################################
# Authentication settings
################################################################################

# Millis conversions cheat sheet:
# 1 second: 1000
# 1 minute: 60000
# 10 minutes: 600000
# 30 minutes: 1800000
# 1 hour: 3600000
# 12 hours: 43200000
# 24 hours: 86400000
# 1 week: 604800000

# Length of time, in milliseconds, that tokens are valid
# default = 3600000
jwt_ttl: 3600000

# Secret for encoding JSON Web Tokens (JWTs)
jwt_secret: 'TOKENsecretHERE'

# Signing algorithm for login tokens
# Must be one of the RSA or ECDSA options listed here:
# https://github.com/auth0/node-jsonwebtoken#algorithms-supported
jwt_signing_alg: 'ES512'

################################################################################
# OpenID Connect settings
################################################################################

# Client ID; this website must be registered with the OpenID Connect provider
# Example: 'f5068d45-c3d2-4ed2-91cf-cbfcfd79ba81'
openid_client_id: 'client'

# Client Secret; this website must be registered with the OpenID Connect provider
# Example: 'AIet9EHpSGRAhhhIElxrJRPXLCGOKN2viG1EwB6jxTKuQeCbLpxX95jAFtILqNPIkgIt29Q4Xgqthq9K8mXJpPo'
openid_client_secret: 'mv42@C0n?'

# Authorization URL of the OpenID Connect provider
openid_url_authorization: '/authorize'

# Token URL of the OpenID Connect provider
openid_url_token: '/token'

# User Info URL of the OpenID Connect provider
openid_url_user_info: '/userinfo'

################################################################################
# Logging options
################################################################################

# Log file path
log_file: 'server.log'

# Log level to use, omits lower log levels
# Levels, lowest to highest: silly, debug, verbose, info, warn, error
# default = 'info'
log_level: 'info'

################################################################################
# Miscellaneous settings
################################################################################

# Name of admin user to be generated by "create-admin" script
admin_user: 'admin@mitre.org'

# Password of admin to be generated by "create-admin" script
# Leaving this blank will generate a random password
#admin_password: 'passw0rd'
